# Generated by Django 4.2.1 on 2023-06-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='refresh_access_token',
            field=models.TextField(unique=True),
        ),
    ]
