# Generated by Django 4.2.1 on 2023-06-05 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Compelete'), ('FUNDRAISING', 'Fundraising'), ('EXPIRED', 'expired')], default='FUNDRAISING', max_length=16),
        ),
        migrations.CreateModel(
            name='Withdrawn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=300)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'withrawns',
            },
        ),
        migrations.CreateModel(
            name='Lend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=300)),
                ('refund_transaction_id', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('LENDED', 'Lended'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=16)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lends',
            },
        ),
    ]
