# Generated by Django 4.2.1 on 2023-06-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_status_withdrawn_lend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Compelete'), ('FUNDRAISING', 'Fundraising'), ('EXPIRED', 'expired')], default='PENDING', max_length=16),
        ),
    ]
