# Generated by Django 4.2.1 on 2023-06-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reach_goal_amount',
            field=models.IntegerField(null=True),
        ),
    ]
