# Generated by Django 4.2.1 on 2023-06-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_reach_goal_amount'),
    ]

    operations = [
        migrations.RunSQL('''
         CREATE OR REPLACE FUNCTION reach_goal_amount_calculate()
          RETURNS TRIGGER AS
          $$
          BEGIN
            UPDATE projects SET reach_goal_amount=reach_goal_amount-NEW.amount WHERE id=NEW.project_id;
            RETURN NEW;
          RETURN NEW;
          END;
          $$
          LANGUAGE PLPGSQL;
         '''),

        migrations.RunSQL('''
        CREATE TRIGGER insert_lends
          AFTER INSERT ON lends FOR EACH ROW EXECUTE FUNCTION reach_goal_amount_calculate();
         ''')
    ]
