# Generated by Django 4.2.1 on 2023-06-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_lend_created_at_lend_updated_at_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lend',
            name='refund_transaction_id',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
