# Generated by Django 4.2.1 on 2023-06-10 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_lend_project_alter_lend_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lend',
            name='withdrawn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lends', to='projects.withdrawn'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
