# Generated by Django 4.2.1 on 2023-06-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_created_at_alter_project_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='withdrawn',
            table='withdrawns',
        ),
    ]
